name: Deploy stack on aws
on:
  push:
    branches:
      - mainnnnnnnnn
jobs:     # We are creating jobs to perofrm steps
  deploy:
    runs-on: ubuntu-latest  # from azure pool
    steps:  # steps to setup cdk and run code
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: checkout git repo code to vm
      uses: actions/checkout@v2


    - name: verify code in vm
      run: ls
    
    - name: install dependencies
      run: |
        cd  wtsoi01-ec2vpc-day33
        npm install
        npm install -g aws-cdk
    
    - name: compile code
      run: |
        cd  wtsoi01-ec2vpc-day33
        cdk synth    

    - name: deploy cdk in aws account
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
      run: |
        cd  wtsoi01-ec2vpc-day33
        cdk deploy --require-approval never

     

   